Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.box = "ubuntu_trusty64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.provision "shell", path: "bootstrap.sh"

  # Grafana Web UI
  config.vm.network "forwarded_port", guest: 80, host: 8082

  # Influx Web UI
  config.vm.network "forwarded_port", guest: 8083, host: 8083

  # Influx API
  config.vm.network "forwarded_port", guest: 8086, host: 8086

end
